### PR TITLE
Implementation of edit file

### PR DESCRIPTION
**Pull request by piskunqa**
1. Added the ability to edit information
examples: 
from cbz import ComicInfo

book = ComicInfo.from_cbz("example.cbz")
print(f"{book.title=} {book.number=}")
book.title = "new title"
book.number = 2
book.save()
print(f"{book.title=} {book.number=}")

results:
first run: 
book.title='title' book.number='1'
book.title='new title' book.number=2
second run:
book.title='new title' book.number='2'
book.title='new title' book.number=2

or 

from cbz import ComicInfo

book = ComicInfo.from_cbz("example.cbz")
book.title = "new title"
book.series = "series"
book.number = 2
book.to_cbz("example2.cbz")
print(ComicInfo.get_info("example.cbz"))
print(ComicInfo.get_info("example2.cbz"))

results:
{'Title': 'title', 'Number': '1', 'Imprint': 'Imprint', 'Format': 'Unknown', 'BlackAndWhite': 'Unknown', 'Manga': 'Unknown', 'AgeRating': 'Unknown'}
{'Title': 'new title', 'Series': 'series', 'Number': '2', 'Imprint': 'Imprint', 'Format': 'Unknown', 'BlackAndWhite': 'Unknown', 'Manga': 'Unknown', 'AgeRating': 'Unknown'}

or 

from cbz import ComicInfo

book = ComicInfo.from_pages([], title="title", number=1)
print(f"{book.title=} {book.number=}")
book.to_cbz("example.cbz")
book.title = "new title"
book.number = 2
book.save()
print(f"{book.title=} {book.number=}")

results:
book.title='title' book.number='1'
book.title='new title' book.number=2

or 

from cbz import ComicInfo

book = ComicInfo.from_pages([], title="title", number=1)
print(f"{book.title=} {book.number=}")
book.title = "new title"
book.number = 2
book.to_cbz("example.cbz")
print(f"{book.title=} {book.number=}")

results:
book.title='title' book.number='1'
book.title='new title' book.number=2

3. Added easy saving to file
comic = ComicInfo.from_pages(...)
comic.to_cbz(<path to save>)
4. Added the ability to read only information from a file without loading images into RAM
ComicInfo.get_info(<path to file>)
6. Fixed a problem with unclosed files (with a large number of class instances it could fill up the RAM and cause a socket error)

### CODE REVIEW

**Review by hyugogirubato — APPROVED** [review]

**Comment by hyugogirubato** [comment]
Using ComicModel is a good idea, but I think that we will have to review the argument type detection system for each option (make sure that it raises ValueError when the type is different).

**Comment by hyugogirubato** [comment]
I will release the pip library update next weekend. If you have other changes to make, don't hesitate! @piskunqa

**Comment by piskunqa** [comment]
> Using ComicModel is a good idea, but I think that we will have to review the argument type detection system for each option (make sure that it raises ValueError when the type is different).

Yes, for this model need to create a controller, I marked it as todo in the code. 
I will do it when I have time

**Comment by hyugogirubato** [comment]
perfect

**Pull request merged**
